version: '3.8'

services:

 ### mysql
  mysql2: 
    image: mysql:8.0.29
    container_name: mysql2 
    ports:
      - 3306:3306 
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pagos_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password123#

 ### Zookeeper
  zookeeper2:
      container_name: zookeeper2
      image: confluentinc/cp-zookeeper:7.4.0
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000

  ### Kafka
  kafka2:
    container_name: kafka2
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper2
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper2:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  ### java
  java_app:
    container_name: java_app
    image: pago_java_app:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:mysql://mysql2:3306/pagos_db
      - DATABASE_USERNAME=user
      - DATABASE_PASSWORD=password123#
    depends_on:
      - mysql2
      - kafka2